# AUTOGENERATED! DO NOT EDIT! File to edit: ..\00_greetings.ipynb.

# %% auto 0
__all__ = ['hello']

# %% ..\00_greetings.ipynb 8
def hello(to):
    return f"Hi {to}!"

# %% ..\00_greetings.ipynb 10
def hello(to): pass
